### ISSUE TITLE
last release version of plugin doesn't work

### ISSUE THREAD

**Issue by MaxSMokeSkaarj** [J-VdS/TeamPlugin#7]
![Screenshot_20210516_192723_io anuke mindustry](https://user-images.githubusercontent.com/62266921/118392491-5e0cda80-b67d-11eb-9950-feef20d28bae.jpg)
![Screenshot_20210516_192803_com sonelli juicessh](https://user-images.githubusercontent.com/62266921/118392556-97dde100-b67d-11eb-95a2-4f9b73aa4342.jpg)

**Comment by j-vds** [comment]
Release version was outdated. Try this [release](https://github.com/J-VdS/TeamPlugin/releases/tag/6.3).
fyi it works and is running in .pl  for several months now.
